// <auto-generated />
using System;
using Fleetmanagement_app_Groep1.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fleetmanagement_app_Groep1.Migrations
{
    [DbContext(typeof(FleetmanagerContext))]
    partial class FleetmanagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Bestuurder", b =>
                {
                    b.Property<string>("PersoneelsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Achternaam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GeboorteDatum")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGearchiveerd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LaatstGeupdate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rijksregisternummer")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("PersoneelsId");

                    b.ToTable("Bestuurder");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Brandstof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeBrandstof")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brandstof");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeWagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Koppeling", b =>
                {
                    b.Property<Guid>("KoppelingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersoneelsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VoertuigId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KoppelingsId");

                    b.HasIndex("PersoneelsId")
                        .IsUnique();

                    b.HasIndex("VoertuigId")
                        .IsUnique()
                        .HasFilter("[VoertuigId] IS NOT NULL");

                    b.ToTable("Koppeling");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Rijbewijs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestuurderPersoneelsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeRijbewijs")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("BestuurderPersoneelsId");

                    b.ToTable("Rijbewijs");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Staat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Voertuig", b =>
                {
                    b.Property<string>("Chassisnummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AantalDeuren")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Bouwjaar")
                        .HasColumnType("int");

                    b.Property<Guid>("BrandstofId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategorieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsGearchiveerd")
                        .HasColumnType("bit");

                    b.Property<string>("Kleur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LaatstGeupdate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nummerplaat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Chassisnummer");

                    b.HasIndex("BrandstofId");

                    b.HasIndex("CategorieId");

                    b.HasIndex("StatusId");

                    b.ToTable("Voertuigen");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Bestuurder", b =>
                {
                    b.OwnsOne("Fleetmanagement_app_Groep1.Entities.Adres", "Adres", b1 =>
                        {
                            b1.Property<string>("BestuurderPersoneelsId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Huisnummer")
                                .HasColumnType("int");

                            b1.Property<int>("Postcode")
                                .HasMaxLength(50)
                                .HasColumnType("int");

                            b1.Property<string>("Stad")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Straat")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BestuurderPersoneelsId");

                            b1.ToTable("Bestuurder");

                            b1.WithOwner("Bestuurder")
                                .HasForeignKey("BestuurderPersoneelsId");

                            b1.Navigation("Bestuurder");
                        });

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Koppeling", b =>
                {
                    b.HasOne("Fleetmanagement_app_Groep1.Entities.Bestuurder", "Bestuurder")
                        .WithOne("Koppeling")
                        .HasForeignKey("Fleetmanagement_app_Groep1.Entities.Koppeling", "PersoneelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fleetmanagement_app_Groep1.Entities.Voertuig", "Voertuig")
                        .WithOne("Koppeling")
                        .HasForeignKey("Fleetmanagement_app_Groep1.Entities.Koppeling", "VoertuigId");

                    b.Navigation("Bestuurder");

                    b.Navigation("Voertuig");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Rijbewijs", b =>
                {
                    b.HasOne("Fleetmanagement_app_Groep1.Entities.Bestuurder", null)
                        .WithMany("Rijbewijzen")
                        .HasForeignKey("BestuurderPersoneelsId");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Voertuig", b =>
                {
                    b.HasOne("Fleetmanagement_app_Groep1.Entities.Brandstof", "Brandstof")
                        .WithMany("Voertuigen")
                        .HasForeignKey("BrandstofId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fleetmanagement_app_Groep1.Entities.Categorie", "Categorie")
                        .WithMany("Voertuigen")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fleetmanagement_app_Groep1.Entities.Status", "Status")
                        .WithMany("Voertuigen")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brandstof");

                    b.Navigation("Categorie");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Bestuurder", b =>
                {
                    b.Navigation("Koppeling");

                    b.Navigation("Rijbewijzen");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Brandstof", b =>
                {
                    b.Navigation("Voertuigen");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Categorie", b =>
                {
                    b.Navigation("Voertuigen");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Status", b =>
                {
                    b.Navigation("Voertuigen");
                });

            modelBuilder.Entity("Fleetmanagement_app_Groep1.Entities.Voertuig", b =>
                {
                    b.Navigation("Koppeling");
                });
#pragma warning restore 612, 618
        }
    }
}
